/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The authenticated user. Inherits the global dual auth, so it serves
         *     both the SPA boot payload (session) and a headless ``whoami`` (bearer).
         *     Read-only — no escalation risk on the bearer path.
         */
        get: operations["core_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List the requesting user's keys, including revoked, newest-first.
         */
        get: operations["api_keys_api_list_api_keys"];
        put?: never;
        /**
         * Create Api Key
         * @description Mint a new key and return the raw token exactly once.
         */
        post: operations["api_keys_api_create_api_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/{api_key_id}/revoke/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Api Key
         * @description Revoke a key. Idempotent. Returns 404 for keys not owned by the
         *     requesting user (existence is not disclosed).
         */
        post: operations["api_keys_api_revoke_api_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MeOut
         * @description The current user, for the SPA boot payload and headless ``whoami``.
         *
         *     Per-user boot data travels through the typed API rather than an untyped
         *     ``window`` global; build-time constants (e.g. project name) are
         *     server-rendered instead. See ADR-0006. Grow as the SPA needs it
         *     (email, is_staff, …) — each field stays inside the OpenAPI contract.
         */
        MeOut: {
            /** Username */
            username: string;
        };
        /**
         * ApiKeyOut
         * @description Wire shape for a UserApiKey row.
         *
         *     Deliberately omits ``hash`` — the persisted token digest is never
         *     surfaced to clients, since the only legitimate consumer of the live
         *     credential is the user who minted it (via the one-shot mint response).
         */
        ApiKeyOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
        };
        /**
         * ApiKeyMintOut
         * @description Response for ``POST /api/api-keys/`` — the only place the raw token
         *     is ever returned by the server.
         */
        ApiKeyMintOut: {
            api_key: components["schemas"]["ApiKeyOut"];
            /** Raw Token */
            raw_token: string;
        };
        /**
         * ApiKeyCreateIn
         * @description Body for ``POST /api/api-keys/``.
         */
        ApiKeyCreateIn: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    api_keys_api_list_api_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
        };
    };
    api_keys_api_create_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyMintOut"];
                };
            };
        };
    };
    api_keys_api_revoke_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                api_key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
        };
    };
}
