"""Dump the project's OpenAPI document to a file.

The schema is generated by importing the shared `NinjaAPI` instance and
asking it for its schema — no running HTTP server is required. The output
feeds `openapi-typescript`, which produces the typed TS declaration
consumed by the SPA's openapi-fetch client.
"""

import json
from pathlib import Path

from django.core.management.base import BaseCommand

from core.api import api


class Command(BaseCommand):
    help = "Dump the OpenAPI schema for the shared NinjaAPI to a file."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--out",
            type=str,
            default="frontend/openapi.json",
            help="Path to write the OpenAPI JSON document to.",
        )

    def handle(self, *args, **options) -> None:
        out_path = Path(options["out"])
        out_path.parent.mkdir(parents=True, exist_ok=True)
        schema = api.get_openapi_schema()
        out_path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n")
        self.stdout.write(self.style.SUCCESS(f"Wrote OpenAPI schema to {out_path}"))
