exclude = [
    "**/__pycache__",
    "**/tests/**",
    "**/test_*",
    "**/migrations/**",
    "**/management/**",
    "manage.py",
]
exact = false
ignore_type_checking_imports = true
forbid_circular_dependencies = true

[[modules]]
path = "core"
depends_on = []
