/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description Bootstrap call that returns runtime config and mints the CSRF cookie.
         *
         *     Calling `get_token` here forces Django to set the `csrftoken` cookie on
         *     the response. The SPA fires this once on startup so subsequent mutations
         *     can read the cookie and attach it as the `X-CSRFToken` header.
         */
        get: operations["core_api_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["example_api_list_projects"];
        put?: never;
        /** Create Project */
        post: operations["example_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["example_api_get_project"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["example_api_delete_project"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["example_api_update_project"];
        trace?: never;
    };
    "/api/example/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["example_api_list_tags"];
        put?: never;
        /** Create Tag */
        post: operations["example_api_create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tag */
        get: operations["example_api_get_tag"];
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["example_api_delete_tag"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["example_api_update_tag"];
        trace?: never;
    };
    "/api/example/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["example_api_list_tasks"];
        put?: never;
        /** Create Task */
        post: operations["example_api_create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["example_api_get_task"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["example_api_delete_task"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["example_api_update_task"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by container healthchecks and the SPA bootstrap.
         */
        get: operations["core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigOut */
        ConfigOut: {
            /** Debug */
            debug: boolean;
            /** Project Name */
            project_name: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedProjectOut */
        PagedProjectOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ProjectOut"][];
        };
        /** PagedTagOut */
        PagedTagOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["TagOut"][];
        };
        /** PagedTaskOut */
        PagedTaskOut: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["TaskOut"][];
        };
        /** ProjectFilters */
        ProjectFilters: {
            /** Status */
            status?: ("draft" | "active" | "archived") | null;
            /** Tag */
            tag?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ProjectIn */
        ProjectIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "active" | "archived";
            /**
             * Tag Ids
             * @default []
             */
            tag_ids: number[];
            /** Title */
            title: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "archived";
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectPatch */
        ProjectPatch: {
            /** Description */
            description?: string | null;
            /** Status */
            status?: ("draft" | "active" | "archived") | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
            /** Title */
            title?: string | null;
        };
        /** TagFilters */
        TagFilters: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** TagIn */
        TagIn: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** TagOut */
        TagOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TagPatch */
        TagPatch: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /** TaskFilters */
        TaskFilters: {
            /** Due From */
            due_from?: string | null;
            /** Due To */
            due_to?: string | null;
            /** Priority */
            priority?: ("low" | "medium" | "high" | "urgent") | null;
            /** Project */
            project?: number | null;
            /** Status */
            status?: ("todo" | "in_progress" | "done" | "blocked") | null;
        };
        /** TaskIn */
        TaskIn: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Due Date */
            due_date?: string | null;
            /**
             * Priority
             * @default medium
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** Project Id */
            project_id: number;
            /**
             * Status
             * @default todo
             * @enum {string}
             */
            status: "todo" | "in_progress" | "done" | "blocked";
            /** Title */
            title: string;
        };
        /** TaskOut */
        TaskOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Due Date */
            due_date: string | null;
            /** Id */
            id: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** Project Id */
            project_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "todo" | "in_progress" | "done" | "blocked";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskPatch */
        TaskPatch: {
            /** Completed At */
            completed_at?: string | null;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Priority */
            priority?: ("low" | "medium" | "high" | "urgent") | null;
            /** Status */
            status?: ("todo" | "in_progress" | "done" | "blocked") | null;
            /** Title */
            title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_api_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    example_api_list_projects: {
        parameters: {
            query?: {
                title?: string | null;
                status?: ("draft" | "active" | "archived") | null;
                tag?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedProjectOut"];
                };
            };
        };
    };
    example_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    example_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    example_api_delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    example_api_update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    example_api_list_tags: {
        parameters: {
            query?: {
                name?: string | null;
                slug?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTagOut"];
                };
            };
        };
    };
    example_api_create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    example_api_get_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    example_api_delete_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    example_api_update_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
        };
    };
    example_api_list_tasks: {
        parameters: {
            query?: {
                project?: number | null;
                status?: ("todo" | "in_progress" | "done" | "blocked") | null;
                priority?: ("low" | "medium" | "high" | "urgent") | null;
                due_from?: string | null;
                due_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTaskOut"];
                };
            };
        };
    };
    example_api_create_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
        };
    };
    example_api_get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
        };
    };
    example_api_delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    example_api_update_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
        };
    };
    core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
